from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

driver_schematic = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'SW_Push_Dual_XKB_Connectivity_TS-1177-B-B-B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_Push_Dual_XKB_Connectivity_TS-1177-B-B-B'}), 'ref_prefix':'SW', 'fplist':['DriverParts:XKB_Connectivity_TS-1177-B-B-B'], 'footprint':'DriverParts:XKB_Connectivity_TS-1177-B-B-B', 'keywords':'switch normally-open pushbutton push-button', 'description':'Push button switch, generic, symbol, four pins', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE),
            Pin(num='3',name='3',func=pin_types.PASSIVE),
            Pin(num='4',name='4',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'ESP32-PICO-V3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESP32-PICO-V3'}), 'ref_prefix':'IC', 'fplist':['DriverParts:ESP32PICOV3'], 'footprint':'DriverParts:ESP32PICOV3', 'keywords':'', 'description':'RF System on a Chip - SoC Module WiFi LGA Dual Core BT Combo', 'datasheet':'https://kr.mouser.com/datasheet/2/891/esp32-pico-v3_datasheet_en-1842685.pdf', 'pins':[
            Pin(num='1',name='VDDA_1',func=pin_types.PASSIVE),
            Pin(num='2',name='LNA_IN',func=pin_types.PASSIVE),
            Pin(num='3',name='VDDA3P3_1',func=pin_types.PASSIVE),
            Pin(num='4',name='VDDA3P3_2',func=pin_types.PASSIVE),
            Pin(num='5',name='SENSOR_VP/I36',func=pin_types.PASSIVE),
            Pin(num='6',name='SENSOR_CAPP/I37',func=pin_types.PASSIVE),
            Pin(num='7',name='SENSOR_CAPN/I38',func=pin_types.PASSIVE),
            Pin(num='8',name='SENSOR_VN/I39',func=pin_types.PASSIVE),
            Pin(num='9',name='EN',func=pin_types.PASSIVE),
            Pin(num='10',name='VDET_1/I34',func=pin_types.PASSIVE),
            Pin(num='11',name='VDET_2/I35',func=pin_types.PASSIVE),
            Pin(num='12',name='32K_XP/IO32',func=pin_types.PASSIVE),
            Pin(num='13',name='32K_XN/IO33',func=pin_types.PASSIVE),
            Pin(num='14',name='IO25',func=pin_types.PASSIVE),
            Pin(num='15',name='IO26',func=pin_types.PASSIVE),
            Pin(num='16',name='IO27',func=pin_types.PASSIVE),
            Pin(num='17',name='MTMS/IO14',func=pin_types.PASSIVE),
            Pin(num='18',name='MTDI/IO12',func=pin_types.PASSIVE),
            Pin(num='19',name='VDD3P3_RTC',func=pin_types.PASSIVE),
            Pin(num='20',name='MTCK/IO13',func=pin_types.PASSIVE),
            Pin(num='21',name='MTDO/IO15',func=pin_types.PASSIVE),
            Pin(num='22',name='IO2',func=pin_types.PASSIVE),
            Pin(num='23',name='IO0',func=pin_types.PASSIVE),
            Pin(num='24',name='IO4',func=pin_types.PASSIVE),
            Pin(num='25',name='NC_1',func=pin_types.PASSIVE),
            Pin(num='26',name='VDD_SDIO',func=pin_types.PASSIVE),
            Pin(num='27',name='IO20',func=pin_types.PASSIVE),
            Pin(num='28',name='SD2/IO9',func=pin_types.PASSIVE),
            Pin(num='29',name='SD3/IO10',func=pin_types.PASSIVE),
            Pin(num='30',name='CMD/IO11',func=pin_types.PASSIVE),
            Pin(num='31',name='CLK/IO6',func=pin_types.PASSIVE),
            Pin(num='32',name='SD0/IO7',func=pin_types.PASSIVE),
            Pin(num='33',name='SD1/IO8',func=pin_types.PASSIVE),
            Pin(num='34',name='IO5',func=pin_types.PASSIVE),
            Pin(num='35',name='NC_2',func=pin_types.PASSIVE),
            Pin(num='36',name='NC_3',func=pin_types.PASSIVE),
            Pin(num='37',name='VDD3P3_CPU',func=pin_types.PASSIVE),
            Pin(num='38',name='IO19',func=pin_types.PASSIVE),
            Pin(num='39',name='IO22',func=pin_types.PASSIVE),
            Pin(num='40',name='U0RXD/IO3',func=pin_types.PASSIVE),
            Pin(num='41',name='U0TXD/IO1',func=pin_types.PASSIVE),
            Pin(num='42',name='IO21',func=pin_types.PASSIVE),
            Pin(num='43',name='VDDA_2',func=pin_types.PASSIVE),
            Pin(num='44',name='NC_4',func=pin_types.PASSIVE),
            Pin(num='45',name='NC_5',func=pin_types.PASSIVE),
            Pin(num='46',name='VDDA_3',func=pin_types.PASSIVE),
            Pin(num='47',name='NC_6',func=pin_types.PASSIVE),
            Pin(num='48',name='NC_7',func=pin_types.PASSIVE),
            Pin(num='49',name='GND',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'LMR36506', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LMR36506'}), 'ref_prefix':'IC', 'fplist':['DriverParts:LMR36506'], 'footprint':'DriverParts:LMR36506', 'keywords':'', 'description':'', 'datasheet':'https://www.ti.com/lit/ds/symlink/lmr36506.pdf', 'pins':[
            Pin(num='1',name='RT',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='PGOOD',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='EN/UVLO',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='VIN',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='SW',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='BOOT',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='VCC',func=pin_types.INPUT,unit=1),
            Pin(num='8',name='FB',func=pin_types.INPUT,unit=1),
            Pin(num='9',name='GND',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MA702GQ-P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MA702GQ-P'}), 'ref_prefix':'IC', 'fplist':['DriverParts:MA702'], 'footprint':'DriverParts:MA702', 'keywords':'', 'description':'Board Mount Hall Effect / Magnetic Sensors 12-bit, digital, contactless angle sensor with ABZ incremental & PWM outputs', 'datasheet':'https://www.monolithicpower.com/pub/media/document/m/a/ma702_r1.0.pdf', 'pins':[
            Pin(num='1',name='SSD/ND',func=pin_types.PASSIVE),
            Pin(num='2',name='A/ERR',func=pin_types.PASSIVE),
            Pin(num='3',name='Z/NVM',func=pin_types.PASSIVE),
            Pin(num='4',name='MOSI',func=pin_types.PASSIVE),
            Pin(num='5',name='CS',func=pin_types.PASSIVE),
            Pin(num='6',name='B/ASC',func=pin_types.PASSIVE),
            Pin(num='7',name='MISO',func=pin_types.PASSIVE),
            Pin(num='8',name='GND_1',func=pin_types.PASSIVE),
            Pin(num='9',name='PWM/DV',func=pin_types.PASSIVE),
            Pin(num='10',name='TEST',func=pin_types.PASSIVE),
            Pin(num='11',name='MGL/NC',func=pin_types.PASSIVE),
            Pin(num='12',name='SCLK',func=pin_types.PASSIVE),
            Pin(num='13',name='VDD',func=pin_types.PASSIVE),
            Pin(num='14',name='NC/VDDIO',func=pin_types.PASSIVE),
            Pin(num='15',name='SSCK/EN',func=pin_types.PASSIVE),
            Pin(num='16',name='MGH/NC',func=pin_types.PASSIVE),
            Pin(num='17',name='GND_2',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'SN65HVD230QDRG4', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SN65HVD230QDRG4'}), 'ref_prefix':'IC', 'fplist':['DriverParts:SN65HVD230QDR'], 'footprint':'DriverParts:SN65HVD230QDR', 'keywords':'', 'description':'3.3-V CAN Transceiver with Standby Mode', 'datasheet':'http://www.ti.com/lit/gpn/sn65hvd230q', 'pins':[
            Pin(num='1',name='D',func=pin_types.PASSIVE),
            Pin(num='2',name='GND',func=pin_types.PASSIVE),
            Pin(num='3',name='VCC',func=pin_types.PASSIVE),
            Pin(num='4',name='R',func=pin_types.PASSIVE),
            Pin(num='5',name='VREF',func=pin_types.PASSIVE),
            Pin(num='6',name='CANL',func=pin_types.PASSIVE),
            Pin(num='7',name='CANH',func=pin_types.PASSIVE),
            Pin(num='8',name='RS',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'XT30PB', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'XT30PB'}), 'ref_prefix':'J', 'fplist':['DriverParts:XT30PB'], 'footprint':'DriverParts:XT30PB', 'keywords':'', 'description':'Mini XT30 Connector', 'datasheet':'https://www.tme.eu/Document/4acc913878197f8c2e30d4b8cdc47230/XT30UPB%20SPEC.pdf', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'SolderJumper_2_Open', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SolderJumper_2_Open'}), 'ref_prefix':'JP', 'fplist':[''], 'footprint':'Jumper:SolderJumper-2_P1.3mm_Open_RoundedPad1.0x1.5mm', 'keywords':'solder jumper SPST', 'description':'Solder Jumper, 2-pole, open', 'datasheet':'', 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='B',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'SolderJumper_3_Bridged12', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SolderJumper_3_Bridged12'}), 'ref_prefix':'JP', 'fplist':[''], 'footprint':'Jumper:SolderJumper-3_P1.3mm_Open_RoundedPad1.0x1.5mm_NumberLabels', 'keywords':'Solder Jumper SPDT', 'description':'3-pole Solder Jumper, pins 1+2 closed/bridged', 'datasheet':'', 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='C',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='B',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'SolderJumper_2_Bridged', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SolderJumper_2_Bridged'}), 'ref_prefix':'JP', 'fplist':[''], 'footprint':'Jumper:SolderJumper-2_P1.3mm_Open_RoundedPad1.0x1.5mm', 'keywords':'solder jumper SPST', 'description':'Solder Jumper, 2-pole, closed/bridged', 'datasheet':'', 'pins':[
            Pin(num='1',name='A',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='B',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'pspice_INDUCTOR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'pspice_INDUCTOR'}), 'ref_prefix':'L', 'fplist':[''], 'footprint':'Inductor_SMD:L_1210_3225Metric', 'keywords':'', 'description':'', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='2',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MountingHole_Pad', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MountingHole_Pad'}), 'ref_prefix':'H', 'fplist':[''], 'footprint':'DriverParts:Motor_Wire_Solder_Pad', 'keywords':'mounting hole', 'description':'Mounting Hole with connection', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0603_1608Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'S3B-ZR-SM4A-TF', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'S3B-ZR-SM4A-TF'}), 'ref_prefix':'P', 'fplist':['DriverParts:SHDR3W50P0X150'], 'footprint':'DriverParts:SHDR3W50P0X150', 'keywords':'', 'description':'', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE),
            Pin(num='3',name='3',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'DRV8316TRGFR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DRV8316TRGFR'}), 'ref_prefix':'U', 'fplist':['DriverParts:DRV8316'], 'footprint':'DriverParts:DRV8316', 'keywords':'', 'description':'', 'datasheet':'', 'pins':[
            Pin(num='1',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='2',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='FB_BK',func=pin_types.UNSPEC,unit=1),
            Pin(num='4',name='GND_BK',func=pin_types.PWRIN,unit=1),
            Pin(num='5',name='SW_BK',func=pin_types.UNSPEC,unit=1),
            Pin(num='6',name='CPL',func=pin_types.UNSPEC,unit=1),
            Pin(num='7',name='CPH',func=pin_types.UNSPEC,unit=1),
            Pin(num='8',name='CP',func=pin_types.UNSPEC,unit=1),
            Pin(num='9',name='VM',func=pin_types.UNSPEC,unit=1),
            Pin(num='10',name='VM',func=pin_types.UNSPEC,unit=1),
            Pin(num='11',name='VM',func=pin_types.UNSPEC,unit=1),
            Pin(num='12',name='PGND',func=pin_types.PWRIN,unit=1),
            Pin(num='13',name='OUTA',func=pin_types.OUTPUT,unit=1),
            Pin(num='14',name='OUTA',func=pin_types.OUTPUT,unit=1),
            Pin(num='15',name='PGND',func=pin_types.PWRIN,unit=1),
            Pin(num='16',name='OUTB',func=pin_types.OUTPUT,unit=1),
            Pin(num='17',name='OUTB',func=pin_types.OUTPUT,unit=1),
            Pin(num='18',name='PGND',func=pin_types.PWRIN,unit=1),
            Pin(num='19',name='OUTC',func=pin_types.OUTPUT,unit=1),
            Pin(num='20',name='OUTC',func=pin_types.OUTPUT,unit=1),
            Pin(num='21',name='DRVOFF',func=pin_types.UNSPEC,unit=1),
            Pin(num='22',name='nFAULT',func=pin_types.UNSPEC,unit=1),
            Pin(num='23',name='nSLEEP',func=pin_types.UNSPEC,unit=1),
            Pin(num='24',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='25',name='AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='26',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='27',name='INHA',func=pin_types.INPUT,unit=1),
            Pin(num='28',name='INLA',func=pin_types.INPUT,unit=1),
            Pin(num='29',name='INHB',func=pin_types.INPUT,unit=1),
            Pin(num='30',name='INLB',func=pin_types.INPUT,unit=1),
            Pin(num='31',name='INHC',func=pin_types.INPUT,unit=1),
            Pin(num='32',name='INLC',func=pin_types.INPUT,unit=1),
            Pin(num='33',name='SDO',func=pin_types.UNSPEC,unit=1),
            Pin(num='34',name='SDI',func=pin_types.UNSPEC,unit=1),
            Pin(num='35',name='SCLK',func=pin_types.UNSPEC,unit=1),
            Pin(num='36',name='nSCS',func=pin_types.UNSPEC,unit=1),
            Pin(num='37',name='VREF/ILIM',func=pin_types.PWRIN,unit=1),
            Pin(num='38',name='SOC',func=pin_types.UNSPEC,unit=1),
            Pin(num='39',name='SOB',func=pin_types.UNSPEC,unit=1),
            Pin(num='40',name='SOA',func=pin_types.UNSPEC,unit=1),
            Pin(num='41',name='EPAD',func=pin_types.UNSPEC,unit=1)], 'unit_defs':[] })])